spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/toy_29cm
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
  jpa:
    hibernate:
      ddl-auto: create 
    properties:
      hibernate:
        show_sql: true #  SQL문이 콘솔에 출력
        format_sql: true # SQL문을 보기 좋게 출력
        use_sql_comments: true # SQL문 이외에 엔티티 정보를 함께 출력
        default_batch_fetch_size: 1000 # select in 기능을 한번에 처리하는 양
    open-in-view: false # open-in-view 기능 off
    database-platform: org.hibernate.dialect.MySQL8Dialect # mysql 버전 8 방언 설정


logging:
  level:
    org.hibernate.SQL: debug # info 보다 debug했을 경우 설명이 더 상세하게 나온다.
    org.hibernate.type: trace #  바인드 파라미터(SQL문 중 물음표로 표기된 부분)를 출력